insert into levels (
  level_number,
  label,
  min_score,
  max_score,
  mission_difficulty_max,
  constraint_difficulty_max,
  shop_tier_max,
  fake_elements_unlocked,
  missions_visible_per_difficulty,
  constraints_visible_per_difficulty,
  privilege_text,
  visible_order
)
values
  (
    1,
    'Niveau 1',
    0,
    4,
    1,
    1,
    1,
    false,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 1. Accès aux contraintes jusqu’à la difficulté 1. Accès à la boutique jusqu’au tier 1. Faux éléments non débloqués. Niveau d’entrée et de découverte du système.',
    1
  ),
  (
    2,
    'Niveau 2',
    5,
    9,
    2,
    2,
    1,
    false,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 2. Accès aux contraintes jusqu’à la difficulté 2. Accès à la boutique jusqu’au tier 1. Faux éléments non débloqués. Niveau de consolidation et d’ouverture stratégique initiale.',
    2
  ),
  (
    3,
    'Niveau 3',
    10,
    15,
    2,
    2,
    2,
    true,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 2. Accès aux contraintes jusqu’à la difficulté 2. Accès à la boutique jusqu’au tier 2. Faux éléments débloqués. Premier palier tactique avancé du système.',
    3
  ),
  (
    4,
    'Niveau 4',
    16,
    24,
    3,
    3,
    2,
    true,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 3. Accès aux contraintes jusqu’à la difficulté 3. Accès à la boutique jusqu’au tier 2. Faux éléments débloqués. Niveau de gameplay avancé et de prise de risque renforcée.',
    4
  ),
  (
    5,
    'Niveau 5',
    25,
    999,
    3,
    3,
    3,
    true,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 3. Accès aux contraintes jusqu’à la difficulté 3. Accès à la boutique jusqu’au tier 3. Faux éléments débloqués. Niveau de maîtrise complète et d’accès total aux options avancées.',
    5
  )
on conflict (level_number) do update
set
  label = excluded.label,
  min_score = excluded.min_score,
  max_score = excluded.max_score,
  mission_difficulty_max = excluded.mission_difficulty_max,
  constraint_difficulty_max = excluded.constraint_difficulty_max,
  shop_tier_max = excluded.shop_tier_max,
  fake_elements_unlocked = excluded.fake_elements_unlocked,
  missions_visible_per_difficulty = excluded.missions_visible_per_difficulty,
  constraints_visible_per_difficulty = excluded.constraints_visible_per_difficulty,
  privilege_text = excluded.privilege_text,
  visible_order = excluded.visible_order,
  updated_at = timezone('utc', now());


insert into element_templates (
  code,
  name,
  element_type,
  category,
  difficulty,
  points,
  duration_minutes,
  skip_unlock_minutes,
  validation_mode,
  proof_required,
  can_be_fake,
  can_appear_in_reserve,
  is_active,
  player_description,
  short_label,
  ui_tags
)
values
  (
    'mission_suspicion_juliette_greg_lou',
    'Rendre Juliette suspecte aux yeux de Greg et Lou',
    'mission',
    'suspicion',
    3,
    5,
    10,
    5,
    'auto',
    false,
    false,
    true,
    true,
    'Rendre Juliette suspecte aux yeux de Greg et Lou',
    'Variante soupçon',
    array['soupçon', 'groupe']::text[]
  ),
  (
    'mission_photo_proof_discrete',
    'Réussir une mission avec une photo discrète montrant clairement la cible et l’action',
    'mission',
    'proof',
    3,
    5,
    10,
    5,
    'proof',
    true,
    false,
    false,
    true,
    'Réussir une mission avec une photo discrète montrant clairement la cible et l’action',
    'Version spéciale preuve',
    array['preuve', 'média']::text[]
  ),
  (
    'mission_recommand_boisson',
    'Faire recommander une boisson à un autre invité',
    'mission',
    'conversation',
    1,
    1,
    5,
    2,
    'auto',
    false,
    false,
    true,
    true,
    'Faire recommander une boisson à un autre invité',
    'Version précisée',
    array['parole', 'boisson']::text[]
  ),
  (
    'constraint_interdit_oui',
    'Interdit : oui',
    'constraint',
    'verbal',
    2,
    2,
    10,
    5,
    'auto',
    false,
    false,
    true,
    true,
    'Interdit : oui',
    '',
    array['verbal', 'interdit']::text[]
  ),
  (
    'constraint_regard_eviter_les_yeux',
    'Regard : éviter les yeux',
    'constraint',
    'behavioral',
    3,
    3,
    15,
    5,
    'gm',
    false,
    false,
    true,
    true,
    'Regard : éviter les yeux',
    '',
    array['comportement', 'regard']::text[]
  ),
  (
    'constraint_reponse_contourner_question',
    'Réponse : contourner la question',
    'constraint',
    'verbal',
    3,
    3,
    15,
    5,
    'auto',
    false,
    false,
    true,
    true,
    'Réponse : contourner la question',
    '',
    array['verbal', 'réponse']::text[]
  )
on conflict (code) do update
set
  name = excluded.name,
  element_type = excluded.element_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  points = excluded.points,
  duration_minutes = excluded.duration_minutes,
  skip_unlock_minutes = excluded.skip_unlock_minutes,
  validation_mode = excluded.validation_mode,
  proof_required = excluded.proof_required,
  can_be_fake = excluded.can_be_fake,
  can_appear_in_reserve = excluded.can_appear_in_reserve,
  is_active = excluded.is_active,
  player_description = excluded.player_description,
  short_label = excluded.short_label,
  ui_tags = excluded.ui_tags,
  updated_at = timezone('utc', now());

insert into players (
  display_name,
  nickname,
  photo_url,
  notes_profile,
  is_active,
  can_play,
  can_be_gm,
  role_tag
)
values
  ('Manon', null, null, null, true, true, false, null),
  ('Mathilde', null, null, null, true, true, false, null),
  ('Yannick', null, null, null, true, true, false, null),
  ('Esteban', null, null, null, true, true, false, null),
  ('Greg', null, null, null, true, true, false, null),
  ('Alexis', null, null, null, true, true, false, null),
  ('Fanny', null, null, null, true, true, false, null),
  ('Chloé', null, null, null, true, true, false, null),
  ('Cédric', null, null, null, true, true, false, null),
  ('Juliette', null, null, null, true, true, false, null),
  ('Lou', null, null, null, true, true, false, null),
  ('Mec de Lou', null, null, null, true, true, false, null),
  ('Lucas', null, null, null, true, true, false, null),
  ('Florentine', null, null, null, true, true, false, null),
  ('Marina', null, null, null, true, true, false, null),
  ('Laurinne', null, null, null, true, true, false, null),
  ('Andy', null, null, null, true, true, false, null),
  ('Adrien', null, null, null, true, false, true, null)
on conflict (display_name) do update
set
  nickname = excluded.nickname,
  photo_url = excluded.photo_url,
  notes_profile = excluded.notes_profile,
  is_active = excluded.is_active,
  can_play = excluded.can_play,
  can_be_gm = excluded.can_be_gm,
  role_tag = excluded.role_tag;

-- TODO: rattacher session_gm_participant_id au participant GM "Adrien" une fois les participants sessionnels seedés.
insert into sessions (
  name,
  session_date,
  location,
  status,
  rules_announced_at,
  game_start_at,
  game_end_at,
  max_active_missions,
  max_active_constraints,
  reserve_per_difficulty,
  fake_unlock_level,
  fake_cycle_every_n_completed,
  bottom_count_for_wheel,
  game_mode,
  notes,
  gm_session_notes,
  session_gm_participant_id
)
values (
  'Jeu des ombres — Anniversaire surprise Manon 27 ans',
  '2026-04-18',
  'Maison de la grand-mère de Manon — préau',
  'preparation',
  timestamptz '2026-04-18 20:30:00 Europe/Paris',
  timestamptz '2026-04-18 21:00:00 Europe/Paris',
  timestamptz '2026-04-18 23:30:00 Europe/Paris',
  2,
  2,
  2,
  3,
  5,
  5,
  'standard',
  '',
  '',
  null
)
on conflict (name) do update
set
  session_date = excluded.session_date,
  location = excluded.location,
  status = excluded.status,
  rules_announced_at = excluded.rules_announced_at,
  game_start_at = excluded.game_start_at,
  game_end_at = excluded.game_end_at,
  max_active_missions = excluded.max_active_missions,
  max_active_constraints = excluded.max_active_constraints,
  reserve_per_difficulty = excluded.reserve_per_difficulty,
  fake_unlock_level = excluded.fake_unlock_level,
  fake_cycle_every_n_completed = excluded.fake_cycle_every_n_completed,
  bottom_count_for_wheel = excluded.bottom_count_for_wheel,
  game_mode = excluded.game_mode,
  notes = excluded.notes,
  gm_session_notes = excluded.gm_session_notes,
  session_gm_participant_id = excluded.session_gm_participant_id,
  updated_at = timezone('utc', now());
