insert into levels (
  level_number,
  label,
  min_score,
  max_score,
  mission_difficulty_max,
  constraint_difficulty_max,
  shop_tier_max,
  fake_elements_unlocked,
  missions_visible_per_difficulty,
  constraints_visible_per_difficulty,
  privilege_text,
  visible_order
)
values
  (
    1,
    'Niveau 1',
    0,
    4,
    1,
    1,
    1,
    false,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 1. Accès aux contraintes jusqu’à la difficulté 1. Accès à la boutique jusqu’au tier 1. Faux éléments non débloqués. Niveau d’entrée et de découverte du système.',
    1
  ),
  (
    2,
    'Niveau 2',
    5,
    9,
    2,
    2,
    1,
    false,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 2. Accès aux contraintes jusqu’à la difficulté 2. Accès à la boutique jusqu’au tier 1. Faux éléments non débloqués. Niveau de consolidation et d’ouverture stratégique initiale.',
    2
  ),
  (
    3,
    'Niveau 3',
    10,
    15,
    2,
    2,
    2,
    true,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 2. Accès aux contraintes jusqu’à la difficulté 2. Accès à la boutique jusqu’au tier 2. Faux éléments débloqués. Premier palier tactique avancé du système.',
    3
  ),
  (
    4,
    'Niveau 4',
    16,
    24,
    3,
    3,
    2,
    true,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 3. Accès aux contraintes jusqu’à la difficulté 3. Accès à la boutique jusqu’au tier 2. Faux éléments débloqués. Niveau de gameplay avancé et de prise de risque renforcée.',
    4
  ),
  (
    5,
    'Niveau 5',
    25,
    999,
    3,
    3,
    3,
    true,
    2,
    2,
    'Accès aux missions jusqu’à la difficulté 3. Accès aux contraintes jusqu’à la difficulté 3. Accès à la boutique jusqu’au tier 3. Faux éléments débloqués. Niveau de maîtrise complète et d’accès total aux options avancées.',
    5
  )
on conflict (level_number) do update
set
  label = excluded.label,
  min_score = excluded.min_score,
  max_score = excluded.max_score,
  mission_difficulty_max = excluded.mission_difficulty_max,
  constraint_difficulty_max = excluded.constraint_difficulty_max,
  shop_tier_max = excluded.shop_tier_max,
  fake_elements_unlocked = excluded.fake_elements_unlocked,
  missions_visible_per_difficulty = excluded.missions_visible_per_difficulty,
  constraints_visible_per_difficulty = excluded.constraints_visible_per_difficulty,
  privilege_text = excluded.privilege_text,
  visible_order = excluded.visible_order,
  updated_at = timezone('utc', now());


insert into element_templates (
  code,
  name,
  element_type,
  category,
  difficulty,
  points,
  duration_minutes,
  skip_unlock_minutes,
  validation_mode,
  proof_required,
  can_be_fake,
  can_appear_in_reserve,
  is_active,
  player_description,
  short_label,
  ui_tags
)
values
  (
    'mission_suspicion_juliette_greg_lou',
    'Rendre Juliette suspecte aux yeux de Greg et Lou',
    'mission',
    'suspicion',
    3,
    5,
    10,
    5,
    'auto',
    false,
    false,
    true,
    true,
    'Rendre Juliette suspecte aux yeux de Greg et Lou',
    'Variante soupçon',
    array['soupçon', 'groupe']::text[]
  ),
  (
    'mission_photo_proof_discrete',
    'Réussir une mission avec une photo discrète montrant clairement la cible et l’action',
    'mission',
    'proof',
    3,
    5,
    10,
    5,
    'proof',
    true,
    false,
    false,
    true,
    'Réussir une mission avec une photo discrète montrant clairement la cible et l’action',
    'Version spéciale preuve',
    array['preuve', 'média']::text[]
  ),
  (
    'mission_recommand_boisson',
    'Faire recommander une boisson à un autre invité',
    'mission',
    'conversation',
    1,
    1,
    5,
    2,
    'auto',
    false,
    false,
    true,
    true,
    'Faire recommander une boisson à un autre invité',
    'Version précisée',
    array['parole', 'boisson']::text[]
  ),
  (
    'constraint_interdit_oui',
    'Interdit : oui',
    'constraint',
    'verbal',
    2,
    2,
    10,
    5,
    'auto',
    false,
    false,
    true,
    true,
    'Interdit : oui',
    '',
    array['verbal', 'interdit']::text[]
  ),
  (
    'constraint_regard_eviter_les_yeux',
    'Regard : éviter les yeux',
    'constraint',
    'behavioral',
    3,
    3,
    15,
    5,
    'gm',
    false,
    false,
    true,
    true,
    'Regard : éviter les yeux',
    '',
    array['comportement', 'regard']::text[]
  ),
  (
    'constraint_reponse_contourner_question',
    'Réponse : contourner la question',
    'constraint',
    'verbal',
    3,
    3,
    15,
    5,
    'auto',
    false,
    false,
    true,
    true,
    'Réponse : contourner la question',
    '',
    array['verbal', 'réponse']::text[]
  )
on conflict (code) do update
set
  name = excluded.name,
  element_type = excluded.element_type,
  category = excluded.category,
  difficulty = excluded.difficulty,
  points = excluded.points,
  duration_minutes = excluded.duration_minutes,
  skip_unlock_minutes = excluded.skip_unlock_minutes,
  validation_mode = excluded.validation_mode,
  proof_required = excluded.proof_required,
  can_be_fake = excluded.can_be_fake,
  can_appear_in_reserve = excluded.can_appear_in_reserve,
  is_active = excluded.is_active,
  player_description = excluded.player_description,
  short_label = excluded.short_label,
  ui_tags = excluded.ui_tags,
  updated_at = timezone('utc', now());

insert into players (
  display_name,
  nickname,
  photo_url,
  notes_profile,
  is_active,
  can_play,
  can_be_gm,
  role_tag
)
values
  ('Manon', null, null, null, true, true, false, null),
  ('Mathilde', null, null, null, true, true, false, null),
  ('Yannick', null, null, null, true, true, false, null),
  ('Esteban', null, null, null, true, true, false, null),
  ('Greg', null, null, null, true, true, false, null),
  ('Alexis', null, null, null, true, true, false, null),
  ('Fanny', null, null, null, true, true, false, null),
  ('Chloé', null, null, null, true, true, false, null),
  ('Cédric', null, null, null, true, true, false, null),
  ('Juliette', null, null, null, true, true, false, null),
  ('Lou', null, null, null, true, true, false, null),
  ('Mec de Lou', null, null, null, true, true, false, null),
  ('Lucas', null, null, null, true, true, false, null),
  ('Florentine', null, null, null, true, true, false, null),
  ('Marina', null, null, null, true, true, false, null),
  ('Laurinne', null, null, null, true, true, false, null),
  ('Andy', null, null, null, true, true, false, null),
  ('Adrien', null, null, null, true, false, true, null)
on conflict (display_name) do update
set
  nickname = excluded.nickname,
  photo_url = excluded.photo_url,
  notes_profile = excluded.notes_profile,
  is_active = excluded.is_active,
  can_play = excluded.can_play,
  can_be_gm = excluded.can_be_gm,
  role_tag = excluded.role_tag;

-- TODO: rattacher session_gm_participant_id au participant GM "Adrien" une fois les participants sessionnels seedés.
insert into sessions (
  name,
  session_date,
  location,
  status,
  rules_announced_at,
  game_start_at,
  game_end_at,
  max_active_missions,
  max_active_constraints,
  reserve_per_difficulty,
  fake_unlock_level,
  fake_cycle_every_n_completed,
  bottom_count_for_wheel,
  game_mode,
  notes,
  gm_session_notes,
  session_gm_participant_id
)
values (
  'Jeu des ombres — Anniversaire surprise Manon 27 ans',
  '2026-04-18',
  'Maison de la grand-mère de Manon — préau',
  'preparation',
  timestamptz '2026-04-18 20:30:00 Europe/Paris',
  timestamptz '2026-04-18 21:00:00 Europe/Paris',
  timestamptz '2026-04-18 23:30:00 Europe/Paris',
  2,
  2,
  2,
  3,
  5,
  5,
  'standard',
  '',
  '',
  null
)
on conflict (name) do update
set
  session_date = excluded.session_date,
  location = excluded.location,
  status = excluded.status,
  rules_announced_at = excluded.rules_announced_at,
  game_start_at = excluded.game_start_at,
  game_end_at = excluded.game_end_at,
  max_active_missions = excluded.max_active_missions,
  max_active_constraints = excluded.max_active_constraints,
  reserve_per_difficulty = excluded.reserve_per_difficulty,
  fake_unlock_level = excluded.fake_unlock_level,
  fake_cycle_every_n_completed = excluded.fake_cycle_every_n_completed,
  bottom_count_for_wheel = excluded.bottom_count_for_wheel,
  game_mode = excluded.game_mode,
  notes = excluded.notes,
  gm_session_notes = excluded.gm_session_notes,
  session_gm_participant_id = excluded.session_gm_participant_id,
  updated_at = timezone('utc', now());

insert into advantage_templates (
  name,
  tier,
  min_player_level,
  cost_tokens,
  visible_if_locked,
  is_active,
  effect_family,
  effect_code,
  target_type,
  duration_seconds,
  is_consumable,
  max_uses,
  description_player,
  description_admin
)
values
  ('Voir un indice sur la mission d’un joueur', 1, 1, 1, true, true, 'investigation', 'reveal_mission_hint', 'other_participant', 0, true, 1, 'Obtiens 1 indice sur la mission d’un joueur.', 'Le MJ fournit un indice partiel sur la mission actuelle ou récente d’un participant ciblé.'),
  ('Voir un indice sur la contrainte d’un joueur', 1, 1, 1, true, true, 'investigation', 'reveal_constraint_hint', 'other_participant', 0, true, 1, 'Obtiens 1 indice sur la contrainte d’un joueur.', 'Le MJ fournit un indice partiel sur la contrainte active ou récente d’un participant ciblé.'),
  ('Savoir si un joueur a une contrainte active', 1, 1, 1, true, true, 'investigation', 'detect_active_constraint', 'other_participant', 0, true, 1, 'Sais si un joueur a actuellement au moins une contrainte active.', 'Le MJ répond uniquement oui/non sur la présence d’au moins une contrainte active chez la cible.'),
  ('Obtenir un indice ciblé sur une personne précise', 1, 1, 1, true, true, 'investigation', 'targeted_person_hint', 'other_participant', 0, true, 1, 'Obtiens un indice ciblé sur une personne précise.', 'Le MJ donne un indice libre mais utile sur la situation ludique de la cible, sans révélation complète.'),
  ('Skip gratuit', 1, 1, 1, true, true, 'tempo', 'free_skip', 'self', 0, true, 1, 'Ignore le malus de ton prochain skip.', 'Permet au joueur de skipper un élément sans perdre les points normalement retirés.'),
  ('Annuler un malus de skip', 1, 1, 1, true, true, 'tempo', 'cancel_skip_penalty', 'self', 0, true, 1, 'Annule un malus de skip déjà subi ou le prochain si besoin.', 'Sert à neutraliser une pénalité de skip ; priorité à un skip déjà subi si applicable, sinon prochain skip.'),
  ('Relancer 1 mission', 2, 3, 2, true, true, 'tempo', 'reroll_one_mission', 'self', 0, true, 1, 'Remplace une mission par une autre du même niveau.', 'Le MJ retire une mission visible ou active du joueur et la remplace par une autre mission cohérente de même difficulté.'),
  ('Relancer 1 contrainte', 2, 3, 2, true, true, 'tempo', 'reroll_one_constraint', 'self', 0, true, 1, 'Remplace une contrainte par une autre du même niveau.', 'Le MJ retire une contrainte visible ou active du joueur et la remplace par une autre contrainte cohérente de même difficulté.'),
  ('Réduire de moitié le temps d’attente d’un slot', 2, 3, 2, true, true, 'tempo', 'halve_slot_cooldown', 'self', 0, true, 1, 'Réduit de moitié le temps d’attente d’un de tes slots.', 'Applique une réduction de 50 % sur le cooldown en cours d’un slot du joueur.'),
  ('Débloquer immédiatement un slot en attente', 2, 3, 2, true, true, 'tempo', 'unlock_slot_now', 'self', 0, true, 1, 'Débloque immédiatement un de tes slots en attente.', 'Supprime entièrement le cooldown d’un slot bloqué du joueur.'),
  ('Bloquer une accusation contre soi pendant 3 minutes', 2, 3, 2, true, true, 'defense', 'accusation_shield_3m', 'self', 0, true, 1, 'Pendant 3 minutes, aucune accusation recevable ne peut être portée contre toi.', 'Pendant 180 secondes, les accusations contre ce joueur sont rejetées ou suspendues selon l’arbitrage MJ.'),
  ('Voir la mission exacte d’un joueur pendant 5 minutes', 3, 5, 3, true, true, 'investigation', 'reveal_exact_mission_5m', 'other_participant', 300, true, 1, 'Vois la mission exacte d’un joueur pendant 5 minutes.', 'Le MJ révèle la mission exacte d’un participant ciblé ; l’avantage est considéré comme actif pendant 300 secondes.'),
  ('Voir la contrainte exacte d’un joueur pendant 5 minutes', 3, 5, 3, true, true, 'investigation', 'reveal_exact_constraint_5m', 'other_participant', 300, true, 1, 'Vois la contrainte exacte d’un joueur pendant 5 minutes.', 'Le MJ révèle la contrainte exacte d’un participant ciblé ; l’avantage est considéré comme actif pendant 300 secondes.'),
  ('Doubler la valeur de la prochaine mission', 3, 5, 3, true, true, 'value', 'double_next_mission_value', 'self', 0, true, 1, 'Ta prochaine mission réussie vaut le double.', 'Double les points de la prochaine mission réussie par le joueur, puis consomme l’avantage.'),
  ('Doubler la valeur de la prochaine contrainte tenue', 3, 5, 3, true, true, 'value', 'double_next_constraint_value', 'self', 0, true, 1, 'Ta prochaine contrainte tenue vaut le double.', 'Double les points de la prochaine contrainte validée comme tenue par le joueur, puis consomme l’avantage.'),
  ('Bonus de 3 jetons si ta prochaine accusation est juste', 3, 5, 3, true, true, 'wager', 'next_correct_accusation_bonus_3', 'self', 0, true, 1, 'Si ta prochaine accusation est juste, gagne 3 jetons enquête bonus.', 'Si la prochaine accusation recevable du joueur est correcte, lui accorder +3 jetons enquête en plus de la récompense normale.'),
  ('Voir la catégorie exacte d’une mission', 2, 3, 2, true, true, 'investigation', 'reveal_mission_category', 'other_participant', 0, true, 1, 'Vois la catégorie exacte d’une mission d’un joueur.', 'Le MJ révèle la catégorie exacte d’une mission active ou récente d’un participant ciblé, sans révéler la mission complète.'),
  ('Accélérer le déblocage d’un slot', 2, 3, 2, true, true, 'tempo', 'accelerate_slot_unlock', 'self', 0, true, 1, 'Accélère le déblocage d’un de tes slots.', 'Réduit partiellement le temps d’attente d’un slot du joueur, sans aller jusqu’au déblocage immédiat complet.'),
  ('Raccourcir ton chrono de contrainte', 2, 3, 2, true, true, 'tempo', 'shorten_own_constraint_timer', 'self', 0, true, 1, 'Raccourcis le chrono de ta contrainte active.', 'Réduit légèrement la durée restante d’une contrainte active du joueur selon l’arbitrage MJ.'),
  ('Réduire ton chrono de contrainte de 50 %', 3, 5, 3, true, true, 'tempo', 'halve_own_constraint_timer', 'self', 0, true, 1, 'Réduis de moitié le chrono de ta contrainte active.', 'Applique une réduction de 50 % au temps restant d’une contrainte active du joueur.'),
  ('Geler temporairement un chrono pendant 1 minute', 3, 5, 3, true, true, 'tempo', 'freeze_timer_60s', 'self', 60, true, 1, 'Gèle temporairement un de tes chronos pendant 1 minute.', 'Suspend le décompte d’un chrono actif du joueur pendant 60 secondes, puis reprend normalement.'),
  ('Échanger une mission active contre une autre de même difficulté', 3, 5, 3, true, true, 'tempo', 'swap_active_mission_same_difficulty', 'self', 0, true, 1, 'Échange une mission active contre une autre de même difficulté.', 'Le MJ retire une mission active du joueur et la remplace par une autre mission cohérente de même difficulté.'),
  ('Échanger une contrainte active contre une autre de même difficulté', 3, 5, 3, true, true, 'tempo', 'swap_active_constraint_same_difficulty', 'self', 0, true, 1, 'Échange une contrainte active contre une autre de même difficulté.', 'Le MJ retire une contrainte active du joueur et la remplace par une autre contrainte cohérente de même difficulté.'),
  ('Annuler un gage', 3, 5, 3, true, true, 'defense', 'cancel_one_penalty', 'self', 0, true, 1, 'Annule un gage qui te vise.', 'Permet de neutraliser un gage attribué au joueur, selon les règles finales et l’arbitrage MJ.'),
  ('Ignorer une accusation', 3, 5, 3, true, true, 'defense', 'ignore_one_accusation', 'self', 0, true, 1, 'Ignore une accusation recevable contre toi.', 'La prochaine accusation recevable contre ce joueur est neutralisée et ne produit aucun effet.'),
  ('Transformer la prochaine accusation juste contre toi en accusation sans récompense', 3, 5, 3, true, true, 'defense', 'deny_reward_on_next_correct_accusation', 'self', 0, true, 1, 'La prochaine accusation juste contre toi ne donne aucune récompense.', 'Si la prochaine accusation recevable contre ce joueur est correcte, elle produit son effet normal mais sans accorder la récompense prévue à l’accusateur.'),
  ('Protéger 1 contrainte jusqu’à la fin de son chrono', 3, 5, 3, true, true, 'defense', 'protect_constraint_until_end', 'self', 0, true, 1, 'Protège une de tes contraintes jusqu’à la fin de son chrono.', 'La contrainte ciblée du joueur ne peut pas être annulée ou affectée par certains effets adverses jusqu’à la fin de son chrono, selon l’arbitrage MJ.'),
  ('Rallonger légèrement le chrono d’une mission d’un autre joueur', 2, 3, 2, true, true, 'pressure', 'extend_other_mission_timer_light', 'other_participant', 0, true, 1, 'Rallonge légèrement le chrono d’une mission d’un autre joueur.', 'Augmente légèrement la durée restante d’une mission active d’un participant ciblé, selon l’arbitrage MJ.'),
  ('Rallonger légèrement le chrono d’une contrainte d’un autre joueur', 2, 3, 2, true, true, 'pressure', 'extend_other_constraint_timer_light', 'other_participant', 0, true, 1, 'Rallonge légèrement le chrono d’une contrainte d’un autre joueur.', 'Augmente légèrement la durée restante d’une contrainte active d’un participant ciblé, selon l’arbitrage MJ.'),
  ('Réduire le chrono d’une mission d’un autre joueur', 3, 5, 3, true, true, 'pressure', 'reduce_other_mission_timer', 'other_participant', 0, true, 1, 'Réduis le chrono d’une mission d’un autre joueur.', 'Réduit la durée restante d’une mission active d’un participant ciblé pour le mettre sous pression.'),
  ('Doubler le chrono d’un joueur sur sa contrainte', 3, 5, 3, true, true, 'pressure', 'double_other_constraint_timer', 'other_participant', 0, true, 1, 'Double le chrono d’un joueur sur sa contrainte.', 'Multiplie par deux la durée restante d’une contrainte active d’un participant ciblé.'),
  ('Diviser par 2 le chrono d’un autre joueur', 3, 5, 3, true, true, 'pressure', 'halve_other_timer', 'other_participant', 0, true, 1, 'Divise par 2 le chrono d’un autre joueur.', 'Réduit de moitié le temps restant d’un chrono actif ciblé chez un autre participant, selon l’arbitrage MJ.'),
  ('Bloquer un contexte chez un autre joueur pendant 15 minutes', 3, 5, 3, true, true, 'pressure', 'block_other_context_15m', 'other_participant', 900, true, 1, 'Bloque un contexte chez un autre joueur pendant 15 minutes.', 'Empêche temporairement un participant ciblé d’exploiter un contexte autorisé par les règles du MJ pendant 900 secondes.'),
  ('Empêcher un joueur d’activer une deuxième mission pendant 5 minutes', 3, 5, 3, true, true, 'pressure', 'block_second_mission_slot_5m', 'other_participant', 300, true, 1, 'Empêche un joueur d’activer une deuxième mission pendant 5 minutes.', 'Pendant 300 secondes, le participant ciblé ne peut pas utiliser son second slot de mission.'),
  ('Empêcher un joueur d’activer une deuxième contrainte pendant 5 minutes', 3, 5, 3, true, true, 'pressure', 'block_second_constraint_slot_5m', 'other_participant', 300, true, 1, 'Empêche un joueur d’activer une deuxième contrainte pendant 5 minutes.', 'Pendant 300 secondes, le participant ciblé ne peut pas utiliser son second slot de contrainte.'),
  ('Forcer un joueur à révéler un indice qu’il possède devant tout le monde', 3, 5, 3, true, true, 'exposure', 'force_public_hint_reveal', 'other_participant', 0, true, 1, 'Force un joueur à révéler un indice qu’il possède devant tout le monde.', 'Le MJ oblige le participant ciblé à révéler publiquement un indice en sa possession, selon les règles de révélation disponibles.')
on conflict (effect_code) do update
set
  name = excluded.name,
  tier = excluded.tier,
  min_player_level = excluded.min_player_level,
  cost_tokens = excluded.cost_tokens,
  visible_if_locked = excluded.visible_if_locked,
  is_active = excluded.is_active,
  effect_family = excluded.effect_family,
  target_type = excluded.target_type,
  duration_seconds = excluded.duration_seconds,
  is_consumable = excluded.is_consumable,
  max_uses = excluded.max_uses,
  description_player = excluded.description_player,
  description_admin = excluded.description_admin,
  updated_at = timezone('utc', now());
